const CarConstant = {
  Name: 'Name',
  Date: 'Date',
  Type: 'Type',
  Model: 'Model',
  Color: 'Color',
  Price: 'Price',
  FuelType: 'Fuel Type',
  Power: 'Power',
  MaximumSpeed: 'Maximum speed (km/h)',
  Length: 'Length',
  Width: 'Width',
  Displacement: 'Displacement (cc)',
  Images: 'Review',
  Equipments: 'Equipments',
  Dealer: 'Dealer',
  Acceleration: '0-100 km/h',
  Upholstery: 'Upholstery',
  Transmission: 'Transmission',
  Torque: 'Torque',
  PageIndexDefault: 1,
  PageSizeDefault: 10,
};
export default CarConstant;
